version: "3.5"

services:
  web:
    image: vue-app
    restart: always
    container_name: frontend-vue
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/var/www/html/app
      #  - /var/www/html/app/node_modules
    environment:
      - npm_config_unsafe_perm=true
    networks:
      - frontend

  api:
    image: node-server
    container_name: node-api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/var/www/html/server

    networks:
      - server

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - public
      - frontend
      - server
      

networks:
  public:
    driver: bridge
  frontend:
    driver: bridge

  server:
    driver: bridge